// Gallery照片配置（确保无重复）
export const galleryPhotos = [
  // 新郎照片 - 5张不同的照片
  {
    id: 1,
    src: '/wedding/Groom主婚单9.jpg',
    category: '新郎',
    title: '新郎 · 张波（主婚照）',
    likes: 128,
    comments: [
      { name: '李明', text: '帅气十足！', time: '10分钟前' },
      { name: '王芳', text: '西装很合身', time: '30分钟前' },
    ],
    linkedMusic: { title: '今天你要嫁给我', artist: '沫言' },
    aspectRatio: '4/3',
  },
  {
    id: 2,
    src: '/wedding/Groom主婚单7.jpg',
    category: '新郎',
    title: '绅士风度（主婚照）',
    likes: 96,
    comments: [],
    aspectRatio: '4/3',
  },
  {
    id: 3,
    src: '/wedding/Groom26.jpg',
    category: '新郎',
    title: '阳光笑容',
    likes: 145,
    comments: [],
    aspectRatio: '9/16',
  },
  {
    id: 4,
    src: '/wedding/Groom27.jpg',
    category: '新郎',
    title: '温柔目光',
    likes: 168,
    comments: [],
    aspectRatio: '4/3',
  },
  {
    id: 5,
    src: '/wedding/Groom28.jpg',
    category: '新郎',
    title: '帅气定格',
    likes: 118,
    comments: [],
    aspectRatio: '9/16',
  },
  
  // 新娘照片 - 5张不同的照片
  {
    id: 6,
    src: '/wedding/Bride-主纱1.jpg',
    category: '新娘',
    title: '新娘 · 邓芮（主婚纱照）',
    likes: 256,
    comments: [{ name: '赵丽', text: '太美了！简直是仙女！', time: '5分钟前' }],
    linkedMusic: { title: '只有你', artist: '沫言' },
    aspectRatio: '4/3',
  },
  {
    id: 7,
    src: '/wedding/Bride-主纱2.jpg',
    category: '新娘',
    title: '优雅绽放（主婚纱照）',
    likes: 192,
    comments: [],
    aspectRatio: '9/16',
  },
  {
    id: 8,
    src: '/wedding/Bride-主纱3.jpg',
    category: '新娘',
    title: '甜蜜微笑（主婚纱照）',
    likes: 210,
    comments: [],
    aspectRatio: '4/3',
  },
  {
    id: 9,
    src: '/wedding/Bride22.jpg',
    category: '新娘',
    title: '美丽瞬间',
    likes: 185,
    comments: [],
    aspectRatio: '9/16',
  },
  {
    id: 10,
    src: '/wedding/Bride23.jpg',
    category: '新娘',
    title: '幸福笑容',
    likes: 240,
    comments: [],
    aspectRatio: '4/3',
  },
  
  // 合照 - 使用主婚合影和动漫合影
  {
    id: 11,
    src: '/wedding/wedding-主婚合影.jpg',
    category: '合照',
    title: '执子之手 · 与子偕老',
    likes: 888,
    comments: [
      { name: '全体祝福', text: '百年好合！白头偕老！', time: '1小时前' },
      { name: '家人', text: '恭喜恭喜！永结同心！', time: '2小时前' },
    ],
    linkedMusic: { title: '爱你一万年', artist: '沫语' },
    aspectRatio: '4/3',
  },
  {
    id: 21,
    src: '/wedding/wedding-主婚合影2.jpg',
    category: '合照',
    title: '幸福时刻（主婚合影）',
    likes: 666,
    comments: [],
    aspectRatio: '4/3',
  },
  {
    id: 22,
    src: '/wedding/wedding-动漫合影2.jpg',
    category: '合照',
    title: '甜蜜瞬间',
    likes: 555,
    comments: [],
    aspectRatio: '9/16',
  },
  {
    id: 23,
    src: '/wedding/wedding-动漫合影1.jpg',
    category: '合照',
    title: '浪漫动漫风',
    likes: 444,
    comments: [],
    aspectRatio: '4/3',
  },
  {
    id: 24,
    src: '/wedding/Wedding-document.jpg',
    category: '合照',
    title: '结婚证照',
    likes: 999,
    comments: [],
    aspectRatio: '4/3',
  },
  
  // 全家福 - 9张不同的照片
  {
    id: 12,
    src: '/wedding/Son5.jpg',
    category: '全家福',
    title: '爱的结晶',
    likes: 384,
    comments: [{ name: '张伟', text: '宝宝好可爱！', time: '1小时前' }],
    aspectRatio: '9/16',
  },
  {
    id: 13,
    src: '/wedding/Son6.jpg',
    category: '全家福',
    title: '幸福时光',
    likes: 288,
    comments: [],
    aspectRatio: '4/3',
  },
  {
    id: 14,
    src: '/wedding/Son7.jpg',
    category: '全家福',
    title: '温馨瞬间',
    likes: 276,
    comments: [],
    aspectRatio: '9/16',
  },
  {
    id: 15,
    src: '/wedding/Son8.jpg',
    category: '全家福',
    title: '童真笑颜',
    likes: 320,
    comments: [],
    aspectRatio: '4/3',
  },
  {
    id: 16,
    src: '/wedding/Son9.jpg',
    category: '全家福',
    title: '快乐成长',
    likes: 245,
    comments: [],
    aspectRatio: '4/3',
  },
  {
    id: 17,
    src: '/wedding/Son10.jpg',
    category: '全家福',
    title: '天真烂漫',
    likes: 298,
    comments: [],
    aspectRatio: '9/16',
  },
  {
    id: 18,
    src: '/wedding/Son11.jpg',
    category: '全家福',
    title: '纯真笑容',
    likes: 276,
    comments: [],
    aspectRatio: '4/3',
  },
  {
    id: 19,
    src: '/wedding/son12.jpg',
    category: '全家福',
    title: '快乐童年',
    likes: 312,
    comments: [],
    aspectRatio: '9/16',
  },
  {
    id: 20,
    src: '/wedding/son14.jpg',
    category: '全家福',
    title: '幸福家庭',
    likes: 352,
    comments: [],
    aspectRatio: '4/3',
  },
]

export const categories = ['全部', '新郎', '新娘', '合照', '全家福']

